### PR TITLE
Cap requests to existing limits, if ControlledValues: RequestsOnly is set

### LINKED ISSUE #97: [BUG] With `ControlledValues: RequestsOnly`, Requests can get higher than Limits
**Describe the bug:**
After [introducing a change to have the HVPA respect the `ControlledValues: RequestsOnly` setting](https://github.com/gardener/hvpa-controller/pull/93), we didn't account for the fact that Requests may get higher than the currently set limit and therefore need to be capped to the Limit. 
The VPA already accounts for this and caps Requests to the Limit if `ControlledValues: RequestsOnly` is set, ~~but as the HVPA may add on top of the VPA recommendations, this isn't true for the HVPA.~~
EDIT: The above statement isn't true. Thanks to @andrerun for asking me about it in a bit more details, such that I tried to hunt down why VPA has recommendations in `target` that **aren't capped to `Limits`**.
The VPA has two places where Recommendation capping is done. :
* [In the recommender](https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-0.10.0/vertical-pod-autoscaler/pkg/recommender/routines/recommender.go#L109), where it might be capped to [`minAllowed` or `maxAllowed` ](https://github.com/kubernetes/autoscaler/blob/6d1a1514af4406bb967ae6f50e9589f7d41f9af8/vertical-pod-autoscaler/pkg/utils/vpa/capping.go#L191-L198)
* [In the admission-controller](https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-0.10.0/vertical-pod-autoscaler/pkg/utils/vpa/capping.go#L87), where it might be [capped to the existing limit in case `controlledValues: RequestsOnly` is set or to an existing `LimitRange` in the namespace](https://github.com/kubernetes/autoscaler/blob/6d1a1514af4406bb967ae6f50e9589f7d41f9af8/vertical-pod-autoscaler/pkg/utils/vpa/capping.go#L103-L140)

And the `VPA` resource's `status` only contains the capping for the `minAllowed` and `maxAllowed` values, but not to `Limits` or `LimitRanges`.

In the end, this leads to the workload becoming un-schedulable like this
```
  Warning  FailedCreate  3m28s (x206 over 2d3h)  statefulset-controller  create Pod etcd-events-0 in StatefulSet etcd-events failed error: Pod "etcd-events-0" is invalid: spec.containers[0].resources.requests: Invalid value: "99m": must be less than or equal to cpu limit
```

**Expected behaviour:**
Never set Requests higher than Limits.

**Environment (please complete the following information):**
 - Hvpa-controller version/commit ID:
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:
Probably just run a "do I need to cap the Requests?" check after computing the new Limit and Requests before actually setting it?

### PR DESCRIPTION
**Pull request by voelzmo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #97

**Special notes for your reviewer**:

**Release note**:

```improvement user
Fix an issue where the HVPA would set Requests higher than Limits if `ControlledValues: RequestsOnly` is set
```

### CODE REVIEW

**Comment by vlerenc** [comment]
Ping... @ashwani2k could you find someone to help review/merge @voelzmo PR, because this problem caused some outages in the past.

cc @dguendisch

**Review by shreyas-s-rao — CHANGES_REQUESTED** [review]
@voelzmo Thanks for the PR! Overall LGTM, except for the failing lint check due to `controllers/hvpa_controller_test.go:331:9: var podCpuLimits should be podCPULimits`. Can you please make this one small fix so that we may merge this? Thanks!

**Review by shreyas-s-rao — APPROVED** [review]

**Pull request merged**
