### PR TITLE
Upgrade golang dependnecies to 1.15.3

### PR DESCRIPTION
**Pull request by mvladev**
**What this PR does / why we need it**:

Upgrade golang dependnecies to 1.15.3. Requirement for #80 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement developer
Golang is upgraded to `1.15.3`.
```

### CODE REVIEW

**Comment by mvladev** [comment]
Okay so the build is failing because it's using the master branch for the pipelines where:

```
Install Golint (linting tool) using go version go1.12.7 linux/amd64 at /tmp/build/d56d9853/pull-request-gardener_hvpa-controller-pr_master
```

the version of golang is 1.12.7 and the build is failing due to bad version vendroing.  Can someone review and directly push it into master?

**Comment by amshuman-kr** [comment]
> the version of golang is 1.12.7 and the build is failing due to bad version vendroing. Can someone review and directly push it into master?

Will do.

**Review by amshuman-kr — APPROVED** [review]
Thanks for the PR @mvladev! ❤️

**Pull request merged**
