### PR TITLE
Adding support of scaling of limits

### PR DESCRIPTION
**Pull request by ggaurav10**
**What this PR does / why we need it**:
Adding support of scaling of limits

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Added files under `hvpa.spec.vpa`
```
    limitsRequestsGapScaleParams:
      cpu:
        percentage: 80
        value: "2"
      memory:
        percentage: 80
        value: 3
```
Following logic is used for scaling of limits:
1. If originalLimit not set, don't set limit.
2. If originalLimit set but originalRequest not set - K8s will treat the pod as if they were equal, then recommend limit equal to request
3. If originalLimit and originalRequest are set. If they are equal recommend limit equal to request.
4. If limit scaling parameters are not set in hvpa.spec.vpa then scale the limits proportionaly as done by VPA
5. If the scaling parameters are provided, then choose the min of the 2 possible values  (percentage and value)

**Release note**:

```improvement operator
Added support of limits scaling
```

### CODE REVIEW

**Review by amshuman-kr — COMMENTED** [review]
Should we cap the limits if a `LimitRange` is applicable?

Some other minor suggestions, otherwise LGTM.

**Comment by ggaurav10** [comment]
> Should we cap the limits if a LimitRange is applicable?

This implementation (PR) is as per our previous discussion that it's better to leave it to the user to set `.spec.vpa.template.spec.resourcePolicy.containerPolicies[].(max/min)Allowed` and `.spec.vpa.limitsScaleParams` in such a way that it doesn't violate `limitRange`'s (if any) max/min allowed.

Taking `limitRange` into account can certainly be an added benefit to the user. As discussed offline earlier, for this, we would need to actively keep a watch on `limitRange` objects, and update all deployments etc. on update of `limitRange` spec, so that any new pod spawned due to HPA or rolling update can have the valid `resources` values. If any of the `requests` or `limits` is not as per `limitRange` spec, then new pod can not be created.
Let's discuss it further if we can come up with a better approach. WDYT?

**Comment by amshuman-kr** [comment]
> This implementation (PR) is as per our previous discussion that it's better to leave it to the user to set `.spec.vpa.template.spec.resourcePolicy.containerPolicies[].(max/min)Allowed` and `.spec.vpa.limitsScaleParams` in such a way that it doesn't violate `limitRange`'s (if any) max/min allowed.

Sorry. My bad. I remembered only part of the conversation and was confused by the fact that `LimitRange` violation would render the `pod` unschedulable. You are right, it is simpler and indeed better to let the user figure it our using `(max|min)Allowed` and limit scale params.

**Review by amshuman-kr — APPROVED** [review]
LGTM

**Pull request merged**
