### PR TITLE
Performance test with >220 node cluster.

### PR DESCRIPTION
**Pull request by amshuman-kr**
**What this PR does / why we need it**:
Performance test results for the review of [#1421@gardener](https://github.com/gardener/gardener/pull/1421).

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by ggaurav10** [comment]
Thanks @amshuman-kr for the PR. The "summary in detail" looks really good.

Although, IMHO, we should also add data/graphs for the following (if possible):
1. Some introduction of the workload (frequency of creating/listing pods/secrets/configmaps, etc.)
1. Number of pods per node
1. Number of pods at any given time
1. Number of secrets (total or per pod)
1. Number of configmaps (total or per pod)
1. Number of watches (cumulative or per resource) for etcd/apiserver
1. Requests per second for apiserver (per VERB maybe - atleast top 2)
1. Explicitly mention that the control plane of the cluster was hosted inside a dedicated cluster/machines (since results could be different when not used in Gardener like architecture)
1. apiserver's latency (...?)

These are the matrices that actually show the reason behind the CPU/memory consumption of apiserver/etcd that we see in our tests. It's relevant to capture the correlation among them. WDYT?

**Comment by amshuman-kr** [comment]
👍 Not sure if I can get graphs for all the points. But will add the points with graphs where possible.

**Comment by amshuman-kr** [comment]
@ggaurav10 I have addressed the review comments. Can you PTAL?

**Review by ggaurav10 — APPROVED** [review]
lgtm

**Pull request merged**
