### PR TITLE
Change in how selector is created for targetRef

### PR DESCRIPTION
**Pull request by ggaurav10**

### CODE REVIEW

**Review by amshuman-kr — CHANGES_REQUESTED** [review]
Looks good. But can you please move the logic to fetch the selector into its own function?

**Review by amshuman-kr — APPROVED** [review]
Thanks. LGTM.

**Comment by ggaurav10** [comment]
Please don't merge yet as I am still working on making the integration test work in the same PR. Or do you suggest to make it a separate PR?

**Comment by ggaurav10** [comment]
Thanks @amshuman-kr for your review. As discussed offline, merging this PR, and will raise a separate PR to fix integration tests.

**Pull request merged**
