### PR TITLE
Update CRD to apiextensions.k8s.io/v1

### PR DESCRIPTION
**Pull request by timuthy**
**What this PR does / why we need it**:
This PR updates the HVPA CRD to `apiextensions.k8s.io/v1`.

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by amshuman-kr — COMMENTED** [review]
Thanks for the PR @timuthy! The changes look good.

The integration tests are failing because `kubebuilder` installation seems to be failing. I will check what's wrong.

```
20:28:26
Downloading and installing kubebuilder...
20:28:27

20:28:27
gzip: stdin: not in gzip format
20:28:27
tar: Child returned status 1
```

**Comment by amshuman-kr** [comment]
> The integration tests are failing because `kubebuilder` installation seems to be failing. I will check what's wrong.

I found that the download URL for kubebuilder releases changed. The following changes succeeded in installing `kubebuilder`.

```patch
diff --git a/.ci/integration_test b/.ci/integration_test
index fa5d6942..696f4542 100755
--- a/.ci/integration_test
+++ b/.ci/integration_test
@@ -46,11 +46,12 @@ function setup_ginkgo(){
 
 function setup_env(){
     echo "Downloading and installing kubebuilder..."
+    version="2.3.1"
     os=$(go env GOOS)
     arch=$(go env GOARCH)
 
     # download kubebuilder and extract it to tmp
-    curl -sL https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/
+    curl -sL https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_${os}_${arch}.tar.gz | tar -xz -C /tmp/
 
     # move to a long-term location and put it on your path
     # (you'll need to set the KUBEBUILDER_ASSETS env var if you put it somewhere else)
```

@timuthy Shall I push this change into this PR or would you prefer if I file a separate PR for this?

**Comment by timuthy** [comment]
@amshuman-kr you can push it to this PR. Thank you very much 👍

**Comment by amshuman-kr** [comment]
> @amshuman-kr you can push it to this PR. Thank you very much 👍

Done in https://github.com/gardener/hvpa-controller/pull/89/commits/c3587affe4009b7189f6006d6aac3fb72c16c247. But I now see the following error.

```
      CustomResourceDefinition.apiextensions.k8s.io "hvpas.autoscaling.k8s.io" is invalid: metadata.annotations[api-approved.kubernetes.io]: Required value: protected groups must have approval annotation "api-approved.kubernetes.io", see https://github.com/kubernetes/enhancements/pull/1111
16:56:41
  occurred

  /tmp/build/8b866f38/pull-request-gardener.hvpa-controller-pr.master/internal/api/v1alpha1/suite_test.go:64
```
@timuthy Do you know anything about it?

**Comment by ggaurav10** [comment]
This has been one of the major blockers for migrating to `v1` from `v1beta1`, and also the reason for advocating for migration to the group `autoscaling.gardener.cloud` (#76).
From what i understood, as per the following link, we need to add an annotation with a link to the PR where API is approved to be included in a "protected group".

**Comment by timuthy** [comment]
Good point @amshuman-kr and @ggaurav10. I forgot to add this here but already did for Gardener, see https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap-crds/charts/hvpa/templates/hvpa.yaml.

**Comment by timuthy** [comment]
The integration test is still failing because it takes the CRD from the wrong path:

```
reading CRDs from path	{"path": "../../../config/crd/bases"}
```

It should be `../../../config/crd/output` instead.

**Review by amshuman-kr — APPROVED** [review]
Thanks for fixing the CRD generation @timuthy 👍

LGTM

**Pull request merged**
